Pull Request for setup-mobile
anita00001/portfolio pull request #1
Opened 2022-10-31 15:43 UTC by anita00001

This is a pull request for branch setup-mobile in the repository portfolio.
This branch contains a README.md file, an index.html file, a style.css file, an images folder to organize images, and linters setup files.

2022-10-31 16:19 UTC, tugsem requested changes
##  STATUS: REQUIRED CHANGES ♻️
Hi @anita00001 , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l0MYC5rnAHehkVKRq/giphy.gif)
## Highlights 🚀 
✔️Github Flow
✔️Linters
✔️Descriptive pr
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-31 16:19 UTC, tugsem commented on index.html
> +
- [ ] Please close your header tag here at line 18 as typically the header tag is used as a page header, it contains the site's title or logo (or both) and the main site navigation.

2022-10-31 16:19 UTC, tugsem commented on style.css
> +  width: 410px;
- [ ] Please remove fixed width here as you are using flexbox to align items responsively according to the different screen sizes. See what I mean on screen size 375px(min):
- your toolbar does have a hamburger button but can't be seen: 
![image](https://user-images.githubusercontent.com/91486791/199054855-0b654905-23b3-49dd-91fe-681db6368794.png)

![image](https://user-images.githubusercontent.com/91486791/199054652-f17e5d31-638d-4390-84cd-5fccf600a6ce.png)

2022-10-31 16:19 UTC, tugsem commented on style.css
> +}
- [ ] Kindly align this button using flexbox only. Make sure you have your button is centered horizontally. Also, add this background image after your button to make your site prettier and match the figma design:
![image](https://user-images.githubusercontent.com/91486791/199056696-95131c8b-53c2-4725-b8b6-eb0078bcf148.png)
add this background image: 
![image](https://user-images.githubusercontent.com/91486791/199056784-c0edf297-0699-43a9-afc2-6b0e718c4654.png)

2022-11-01 08:26 UTC, sajid-munawar approved these changes
### Hi @anita00001 , 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:
 
 ## [Optional] suggestions:
 * [ ]  Please check my inline comments.
 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @sajid-munawar in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-01 08:33 UTC, merged